#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

source_dir="out/evidence-source"
payload_dir="${source_dir}/payloads"

python3 demo/incident_replay.py --no-send --output-dir "${source_dir}" --payload-dir "${payload_dir}" >/dev/null
python3 demo/reliability_gate.py \
  --summary "${source_dir}/summary.json" \
  --slo-config config/reliability-slo.json \
  --output-dir docs/evidence >/dev/null
python3 demo/capacity_planner.py \
  --summary "${source_dir}/summary.json" \
  --slo-config config/reliability-slo.json \
  --output-dir docs/evidence >/dev/null
python3 demo/runbook_generator.py \
  --summary "${source_dir}/summary.json" \
  --gate docs/evidence/reliability-gate.json \
  --output-dir docs/evidence >/dev/null
python3 demo/advanced_reliability.py \
  --summary "${source_dir}/summary.json" \
  --payload-dir "${payload_dir}" \
  --slo-config config/reliability-slo.json \
  --advanced-config config/advanced-reliability.json \
  --output-dir docs/evidence >/dev/null
python3 demo/detailed_reliability.py \
  --summary "${source_dir}/summary.json" \
  --payload-dir "${payload_dir}" \
  --detailed-config config/detailed-reliability.json \
  --output-dir docs/evidence >/dev/null
python3 demo/deployment_policy.py \
  --gate docs/evidence/reliability-gate.json \
  --burn-rate docs/evidence/burn-rate-analysis.json \
  --rollout-guard docs/evidence/rollout-guard.json \
  --trace-quality docs/evidence/trace-quality-audit.json \
  --collector-resilience docs/evidence/collector-resilience.json \
  --hpa-lag docs/evidence/hpa-lag-analysis.json \
  --tenant-blast-radius docs/evidence/tenant-blast-radius.json \
  --token-cost-guard docs/evidence/token-cost-guard.json \
  --output-dir docs/evidence >/dev/null
python3 demo/policy_regression_suite.py \
  --fixtures config/deployment-policy-fixtures.json \
  --output-dir docs/evidence >/dev/null
python3 demo/supply_chain_audit.py \
  --policy config/supply-chain-policy.json \
  --repo-root . \
  --output-dir docs/evidence >/dev/null
python3 demo/k8s_hardening_audit.py \
  --policy config/k8s-hardening-policy.json \
  --repo-root . \
  --output-dir docs/evidence >/dev/null
python3 demo/admission_policy_audit.py \
  --policy config/admission-policy.json \
  --repo-root . \
  --output-dir docs/evidence >/dev/null
python3 demo/alerting_rules.py \
  --slo-config config/reliability-slo.json \
  --policy config/alerting-policy.json \
  --output-dir docs/evidence \
  --manifest k8s/gke/alerting-rules.yaml >/dev/null
python3 demo/grafana_dashboard.py \
  --slo-config config/reliability-slo.json \
  --alert-policy config/alerting-policy.json \
  --dashboard-policy config/dashboard-policy.json \
  --output-dir docs/evidence \
  --dashboard dashboards/grafana/gke-ai-inference-reliability.json \
  --config-map k8s/gke/grafana-dashboard-configmap.yaml >/dev/null
python3 demo/openslo_contract.py \
  --slo-config config/reliability-slo.json \
  --alert-policy config/alerting-policy.json \
  --openslo-policy config/openslo-policy.json \
  --output-dir docs/evidence \
  --contract slos/openslo/gke-ai-inference-slo.yaml >/dev/null
python3 demo/telemetry_redaction_audit.py \
  --summary "${source_dir}/summary.json" \
  --payload-dir "${payload_dir}" \
  --policy config/telemetry-redaction-policy.json \
  --output-dir docs/evidence >/dev/null
python3 demo/telemetry_cost_budget.py \
  --summary "${source_dir}/summary.json" \
  --payload-dir "${payload_dir}" \
  --policy config/telemetry-cost-policy.json \
  --output-dir docs/evidence >/dev/null
python3 demo/error_budget_ledger.py \
  --summary "${source_dir}/summary.json" \
  --slo-config config/reliability-slo.json \
  --openslo-policy config/openslo-policy.json \
  --error-budget-policy config/error-budget-policy.json \
  --output-dir docs/evidence >/dev/null
python3 demo/rollback_drill.py \
  --summary "${source_dir}/summary.json" \
  --runbooks docs/evidence/incident-runbooks.json \
  --deployment-policy docs/evidence/deployment-policy.json \
  --error-budget docs/evidence/error-budget-ledger.json \
  --drill-policy config/rollback-drill-policy.json \
  --output-dir docs/evidence >/dev/null
python3 demo/post_incident_review.py \
  --summary "${source_dir}/summary.json" \
  --incident-correlation docs/evidence/incident-correlation.json \
  --rollback-drill docs/evidence/rollback-drill.json \
  --error-budget docs/evidence/error-budget-ledger.json \
  --deployment-policy docs/evidence/deployment-policy.json \
  --policy config/post-incident-review-policy.json \
  --output-dir docs/evidence >/dev/null
python3 demo/release_waiver_governance.py \
  --policy config/release-waiver-policy.json \
  --waivers config/release-waivers.json \
  --deployment-policy docs/evidence/deployment-policy.json \
  --error-budget docs/evidence/error-budget-ledger.json \
  --rollback-drill docs/evidence/rollback-drill.json \
  --post-incident-review docs/evidence/post-incident-review.json \
  --output-dir docs/evidence >/dev/null
python3 demo/disaster_recovery_drill.py \
  --repo-root . \
  --policy config/disaster-recovery-policy.json \
  --restore-dir out/disaster-recovery-restore \
  --output-dir docs/evidence >/dev/null
python3 demo/render_incident_evidence.py \
  --input "${source_dir}/summary.json" \
  --output-dir docs/evidence
python3 demo/evidence_provenance.py \
  --policy config/evidence-provenance-policy.json \
  --repo-root . \
  --output-dir docs/evidence >/dev/null
python3 demo/release_readiness.py \
  --gate docs/evidence/reliability-gate.json \
  --capacity docs/evidence/capacity-plan.json \
  --runbooks docs/evidence/incident-runbooks.json \
  --advanced docs/evidence/complex-problems.json \
  --detailed docs/evidence/detailed-problems.json \
  --policy docs/evidence/deployment-policy.json \
  --policy-regression docs/evidence/policy-regression-suite.json \
  --supply-chain docs/evidence/supply-chain-audit.json \
  --k8s-hardening docs/evidence/k8s-hardening-audit.json \
  --admission-policy docs/evidence/admission-policy-audit.json \
  --alerting docs/evidence/alerting-rules.json \
  --dashboard docs/evidence/grafana-dashboard.json \
  --openslo docs/evidence/openslo-contract.json \
  --telemetry-redaction docs/evidence/telemetry-redaction-audit.json \
  --telemetry-cost docs/evidence/telemetry-cost-budget.json \
  --error-budget docs/evidence/error-budget-ledger.json \
  --rollback-drill docs/evidence/rollback-drill.json \
  --post-incident-review docs/evidence/post-incident-review.json \
  --release-waiver-governance docs/evidence/release-waiver-governance.json \
  --disaster-recovery-drill docs/evidence/disaster-recovery-drill.json \
  --evidence-provenance docs/evidence/evidence-provenance.json \
  --evidence-dir docs/evidence \
  --output-dir docs/evidence >/dev/null

echo "evidence generated under docs/evidence"
